# Generated by Django 4.2.20 on 2025-04-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cedula',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
