# Generated by Django 4.2.19 on 2025-03-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='checkForTI',
            field=models.BooleanField(default=False),
        ),
    ]
