# Generated by Django 5.1.6 on 2025-02-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitaProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagaduria', models.CharField(max_length=255, verbose_name='Pagaduría')),
                ('asesor', models.CharField(max_length=255, verbose_name='Asesor Asignado')),
                ('fecha', models.DateField(verbose_name='Fecha de la Cita')),
                ('hora', models.TimeField(verbose_name='Hora de la Cita')),
            ],
        ),
    ]
