# Generated by Django 5.1.6 on 2025-03-03 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pagaduria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='citaprogramada',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='citaprogramada',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='citaprogramada',
            name='asesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.asesor'),
        ),
        migrations.AlterField(
            model_name='citaprogramada',
            name='pagaduria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.pagaduria'),
        ),
    ]
