# Generated by Django 4.2.19 on 2025-04-07 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagadurias', '0006_alter_pagaduria_tokencontrol'),
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asesor',
        ),
        migrations.AlterField(
            model_name='citaprogramada',
            name='asesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Asesor'),
        ),
        migrations.AlterField(
            model_name='citaprogramada',
            name='pagaduria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagadurias.pagaduria', verbose_name='Pagaduría'),
        ),
        migrations.DeleteModel(
            name='Pagaduria',
        ),
    ]
