# Generated by Django 5.1.6 on 2025-03-14 15:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_asesor_pagaduria_alter_citaprogramada_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asesor',
            options={'ordering': ['nombre'], 'verbose_name': 'Asesor', 'verbose_name_plural': 'Asesores'},
        ),
        migrations.AlterModelOptions(
            name='citaprogramada',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'Cita Programada', 'verbose_name_plural': 'Citas Programadas'},
        ),
        migrations.AlterModelOptions(
            name='pagaduria',
            options={'ordering': ['nombre'], 'verbose_name': 'Pagaduría', 'verbose_name_plural': 'Pagadurías'},
        ),
        migrations.AddField(
            model_name='citaprogramada',
            name='estado',
            field=models.CharField(choices=[('programada', 'Programada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='citaprogramada',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='citaprogramada',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='citaprogramada',
            name='ultima_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AlterField(
            model_name='citaprogramada',
            name='asesor',
            field=models.CharField(max_length=255, verbose_name='Asesor'),
        ),
        migrations.AlterField(
            model_name='citaprogramada',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='citaprogramada',
            name='hora',
            field=models.TimeField(verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='citaprogramada',
            name='pagaduria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citas.pagaduria', verbose_name='Pagaduría'),
        ),
        migrations.AlterUniqueTogether(
            name='citaprogramada',
            unique_together={('fecha', 'hora')},
        ),
    ]
