# Generated by Django 4.2.20 on 2025-04-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_delete_asesor_alter_citaprogramada_asesor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citaprogramada',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='citaprogramada',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='citaprogramada',
            name='estado',
            field=models.CharField(choices=[('Programada', 'Programada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Programada', max_length=20, verbose_name='Estado'),
        ),
    ]
