# Generated by Django 4.2.19 on 2025-05-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_citaprogramada_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citaprogramada',
            name='resultado',
            field=models.TextField(blank=True, null=True, verbose_name='resultado'),
        ),
        migrations.AlterField(
            model_name='citaprogramada',
            name='estado',
            field=models.CharField(choices=[('Programada', 'Programada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada'), ('Atencion', 'Atencion')], default='Programada', max_length=20, verbose_name='Estado'),
        ),
    ]
