# Generated by Django 5.1.6 on 2025-03-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_alter_asesor_options_alter_citaprogramada_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citaprogramada',
            name='estado',
            field=models.CharField(choices=[('Programada', 'Programada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='Estado'),
        ),
    ]
