# Generated by Django 4.2.20 on 2025-05-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_citaprogramada_resultado_alter_citaprogramada_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citaprogramada',
            name='estado',
            field=models.CharField(choices=[('Programada', 'Programada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada'), ('En atención', 'En atención')], default='Programada', max_length=20, verbose_name='Estado'),
        ),
    ]
