# Generated by Django 5.1.6 on 2025-03-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_update_estado_choices'),
        ('citas', '0004_alter_citaprogramada_estado'),
    ]

    operations = [
    ]
