# Generated by Django 5.1.6 on 2025-02-26 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagaduria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Pagaduría')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('empleados', models.IntegerField(verbose_name='Número de Empleados')),
                ('estado', models.CharField(choices=[('Por aprobar', 'Por aprobar'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Por aprobar', max_length=20, verbose_name='Estado')),
                ('asesor', models.CharField(max_length=255, verbose_name='Asesor Asignado')),
            ],
        ),
    ]
