# Generated by Django 5.2 on 2025-04-02 15:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagaduria',
            name='tokenControl',
            field=models.UUIDField(blank=True, default=uuid.UUID('f3fba603-ae78-4668-a3bc-0d9902dfc42a'), editable=False, null=True),
        ),
    ]
