# Generated by Django 4.2.19 on 2025-03-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagaduria',
            name='estado',
            field=models.CharField(blank=True, default='Por aprobar', max_length=200, null=True),
        ),
    ]
