# Generated by Django 5.1.6 on 2025-03-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagaduria',
            name='commercial_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagaduria',
            name='financial_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagaduria',
            name='risk_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
