# Generated by Django 4.2.19 on 2025-03-20 14:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagaduria',
            name='tokenControl',
            field=models.UUIDField(blank=True, default=uuid.UUID('3fe4fc39-21f1-42d1-ba8e-89a3e8d93782'), editable=False, null=True),
        ),
    ]
