# Generated by Django 4.2.19 on 2025-03-25 20:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0002_pagaduria_tokencontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagaduria',
            name='actividadEconomica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='asesorAsignado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='asesorCreated',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='camaraComercio',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='cedulaRepresentante',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='centrales',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='ciudad',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='composicionAccionaria',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='convenio',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='correoRepresentante',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='declaracionRenta',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='departamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='direccion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='empleadosFijo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='empleadosIndefinidos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='empleadosObraLabor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='empleadosOtros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='empleadosSalario1y2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='empleadosSalario2y4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='empleadosSalariomax4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='encargadoEnvioCuentaCargo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='encargadoEnvioCuentaCorreo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='encargadoEnvioCuentaDireccion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='encargadoEnvioCuentaNombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='encargadoEnvioCuentaTelefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='encargadoVisacionCargo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='encargadoVisacionCorreo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='encargadoVisacionDireccion',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='encargadoVisacionNombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='encargadoVisacionTelefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='estadosFinancieros',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='fechaCreacion',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='fechaMaxEnvioCuentaCobro',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='formulariovinculacion',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='maxDescuentoNomina',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='nombreRepresentante',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='numeroCedulaRepresentante',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='razonSocial',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='rut',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='sigla',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='tarjetasFirma',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='tipoEmpresa',
            field=models.CharField(blank=True, choices=[('Pública', 'Pública'), ('Descentralizada', 'Descentralizada'), ('Privada', 'Privada'), ('Sin ánimo de lucro', 'Sin ánimo de lucro')], max_length=100, null=True, verbose_name='Tipo de Empresa'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='tokenControl',
            field=models.UUIDField(blank=True, default=uuid.UUID('3021c057-c253-4f2a-b34a-c5d907eb9a0f'), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='totalEmpleados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='visacionLibranza',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='visacionMedio',
            field=models.CharField(blank=True, choices=[('Correo', 'Correo'), ('Fisico', 'Fisico')], max_length=20, null=True),
        ),
    ]
