# Generated by Django 4.2.19 on 2025-04-04 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0002_alter_pagaduria_tokencontrol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secursalespgaduria',
            old_name='nombreSucursale',
            new_name='ciudad',
        ),
        migrations.AddField(
            model_name='secursalespgaduria',
            name='departamento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='tokenControl',
            field=models.UUIDField(blank=True, default=uuid.UUID('cacf14bc-b7df-48eb-b3ef-ca5960be015a'), editable=False, null=True),
        ),
    ]
