# Generated by Django 5.1.6 on 2025-03-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0002_pagaduria_commercial_score_pagaduria_financial_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagaduria',
            name='estado_comercial',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pagaduria',
            name='estado_financiero',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pagaduria',
            name='estado_riesgos',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
    ]
