# Generated by Django 4.2.19 on 2025-04-07 15:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0003_rename_nombresucursale_secursalespgaduria_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagaduria',
            name='tokenControl',
            field=models.UUIDField(blank=True, default=uuid.UUID('5d153ded-1fa6-407e-a0a4-08106b7b1357'), editable=False, null=True),
        ),
        migrations.CreateModel(
            name='ObservacionesPagaduria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(max_length=2000)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('creadoPor', models.CharField(max_length=200)),
                ('pagaduria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacion', to='pagadurias.pagaduria')),
            ],
        ),
    ]
