# Generated by Django 4.2.19 on 2025-04-07 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0004_alter_pagaduria_tokencontrol_observacionespagaduria'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacionespagaduria',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='observacionespagaduria',
            name='observacion',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='tokenControl',
            field=models.UUIDField(blank=True, default=uuid.UUID('d6d9d325-533c-40ea-9858-042b65145450'), editable=False, null=True),
        ),
    ]
