# Generated by Django 4.2.19 on 2025-03-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0003_alter_pagaduria_tokencontrol'),
        ('pagadurias', '0004_alter_pagaduria_numerocedularepresentante_and_more'),
    ]

    operations = [
    ]
