# Generated by Django 4.2.19 on 2025-04-07 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0005_observacionespagaduria_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagaduria',
            name='tokenControl',
            field=models.UUIDField(blank=True, default=uuid.UUID('b96fe93f-3c0d-4c18-95c3-917e9941e7ee'), editable=False, null=True),
        ),
    ]
