# Generated by Django 4.2.19 on 2025-04-01 14:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0005_merge_20250325_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagaduria',
            name='empleadosFijo',
        ),
        migrations.RemoveField(
            model_name='pagaduria',
            name='empleadosIndefinidos',
        ),
        migrations.RemoveField(
            model_name='pagaduria',
            name='empleadosObraLabor',
        ),
        migrations.RemoveField(
            model_name='pagaduria',
            name='empleadosOtros',
        ),
        migrations.RemoveField(
            model_name='pagaduria',
            name='empleadosSalario1y2',
        ),
        migrations.RemoveField(
            model_name='pagaduria',
            name='empleadosSalario2y4',
        ),
        migrations.RemoveField(
            model_name='pagaduria',
            name='empleadosSalariomax4',
        ),
        migrations.RemoveField(
            model_name='pagaduria',
            name='totalEmpleados',
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='tokenControl',
            field=models.UUIDField(blank=True, default=uuid.UUID('2c91c85e-1c0f-4716-b0e8-4fa4691d7767'), editable=False, null=True),
        ),
        migrations.CreateModel(
            name='SecursalesPgaduria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreSucursale', models.CharField(blank=True, max_length=200, null=True)),
                ('totalEmpleados', models.IntegerField(blank=True, null=True)),
                ('empleadosIndefinidos', models.IntegerField(blank=True, null=True)),
                ('empleadosFijo', models.IntegerField(blank=True, null=True)),
                ('empleadosObraLabor', models.IntegerField(blank=True, null=True)),
                ('empleadosOtros', models.IntegerField(blank=True, null=True)),
                ('empleadosSalario1y2', models.IntegerField(blank=True, null=True)),
                ('empleadosSalario2y4', models.IntegerField(blank=True, null=True)),
                ('empleadosSalariomax4', models.IntegerField(blank=True, null=True)),
                ('pagaduria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='pagadurias.pagaduria')),
            ],
        ),
    ]
