# Generated by Django 5.2 on 2025-04-10 15:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0008_alter_pagaduria_tokencontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagaduria',
            name='tokenControl',
            field=models.UUIDField(blank=True, default=uuid.UUID('aa5e55be-b3a0-4d23-8ad9-f86eab3fea5f'), editable=False, null=True),
        ),
    ]
