# Generated by Django 4.2.20 on 2025-04-23 16:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0009_alter_pagaduria_tokencontrol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecursalesPgaduria',
            new_name='SucursalesPagaduria',
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='estadoComercial',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado por Politicas', 'Rechazado por Politicas'), ('Rechazado por Documentación', 'Rechazado por Documentación')], default='Pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='estadoFinanciero',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado por Politicas', 'Rechazado por Politicas'), ('Rechazado por Documentación', 'Rechazado por Documentación')], default='Pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='estadoRiesgos',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado por Politicas', 'Rechazado por Politicas'), ('Rechazado por Documentación', 'Rechazado por Documentación')], default='Pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='fechaMaxEnvioCuentaCobro',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='tokenControl',
            field=models.UUIDField(blank=True, default=uuid.UUID('3bff61c2-23de-4962-ad70-70bb62672557'), editable=False, null=True),
        ),
    ]
