# Generated by Django 4.2.19 on 2025-04-28 13:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0011_pagaduria_asesores_pagaduria_estadooperaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagaduria',
            name='tokenControl',
            field=models.UUIDField(blank=True, default=uuid.UUID('abba05ce-0631-4e7b-a23a-ec0e0e5b02b2'), editable=False, null=True),
        ),
    ]
