# Generated by Django 4.2.20 on 2025-05-02 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pagadurias', '0012_alter_pagaduria_tokencontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagaduria',
            name='tokenControl',
            field=models.UUIDField(blank=True, default=uuid.UUID('fc3a024f-3ffd-4fc0-a8bd-71d82c957ed1'), editable=False, null=True),
        ),
        migrations.CreateModel(
            name='HistorialPagaduria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creación', 'Creación'), ('actualización', 'Actualización'), ('cambio_estado', 'Cambio de Estado'), ('aprobacion', 'Aprobacion por Área'), ('rechazo', 'Rechazo por Área')], max_length=50)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pagaduria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagadurias.pagaduria')),
                ('realizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
