# Generated by Django 4.2.19 on 2025-05-05 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0013_alter_pagaduria_tokencontrol_historialpagaduria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagaduria',
            name='tokenControl',
            field=models.UUIDField(blank=True, default=uuid.UUID('1276acb4-a37b-481d-9f3b-27007147655f'), editable=False, null=True),
        ),
    ]
