# Generated by Django 4.2.19 on 2025-05-12 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pagadurias', '0014_alter_pagaduria_tokencontrol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagaduria',
            name='analisisRiesgos',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='camaraComercio',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='cedulaRepresentante',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='centrales',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='composicionAccionaria',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='convenio',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='declaracionRenta',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='estadosFinancieros',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='formulariovinculacion',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='rut',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='scoreComercial',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='scoreFinanciero',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='tarjetasFirma',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pagaduria',
            name='tokenControl',
            field=models.UUIDField(blank=True, default=uuid.UUID('42b45d12-fc2c-4cc0-a9a8-c10c72e9f97d'), editable=False, null=True),
        ),
    ]
